---
title: "From Code to Paper: Reproducible Research with Quarto"
author: "Betsabe Cohen (BA Sociology)"
format: 
  revealjs:
    theme: simple
    slide-number: true
    chalkboard: 
      buttons: true
editor: 
  markdown: 
    wrap: sentence
theme: minty
---

## Hello/ Hola!

My name is Betsabé Cohen I'm a sociologist and data analyst from Buenos Aires Argentina
I'm 
....

## Agenda

::: incremental

-   Why Reproducibility?

-   What is Quarto?

-   Core Use Cases

-   Academic Production with Quarto Manuscripts

-   Tips on Practical Reproducibility: GitHub Integration

-   Hands-on Coding

-   Learning More & Getting Involved
:::


# Why Reproducibility?

## What do we mean by reproductibility

## Reporductible code

## Building reproductibility with Git and GitHub


# What is Quarto?

## Analyze. Share. Reproduce

-   An open-source scientific and technical publishing system

-   Create dynamic content with Python, R, Julia, and Observable.

-   Publish reproducible, production quality articles, presentations, dashboards, websites, blogs, and books in HTML, PDF, MS Word, ePub, and more.

-   Share knowledge and insights organization-wide by publishing to Posit Connect, Confluence, or other publishing systems.

-   Write using Pandoc markdown, including equations, citations, crossrefs, figure panels, callouts, advanced layout, and more.


## Quarto for R

-   A multi-language, next generation version of R Markdown from Posit, with many new features and capabilities. 

-   Like R Markdown, Quarto uses knitr to execute R code, and is therefore able to render most existing Rmd files without modification.


# Core Use Cases

## Dynamic Documents

Generate dynamic output using Python, R, Julia, and Observable. Create reproducible documents that can be regenerated when underlying assumptions or data change.

## Beautiful Publications

Publish high-quality articles, reports, presentations, websites, and books in HTML, PDF, MS Word, ePub, and more. Use a single source document to target multiple formats.

## Scientific Markdown

Pandoc markdown has excellent support for LaTeX equations and citations. Quarto adds extensions for cross-references, figure panels, callouts, advanced page layout, and more.

## Websites and Books

Publish collections of documents as a blog or full website. Create books and manuscripts in both print formats (PDF and MS Word) and online formats (HTML and ePub).


## Interactivity

Engage readers by adding interactive data exploration to your documents using Jupyter Widgets, htmlwidgets for R, Observable JS, and Shiny.


# Academic Production with Quarto Manuscripts




# Tips on Practical Reproducibility: GitHub Integration


# Hands-on Coding




